version: '3.7'

services:
  apiserver:
    image: aimi614/docker_wechat:latest
    container_name: wcf-server-v3.9.11.25
#    restart: unless-stopped
    tty: true
    ports:
      - "10086:8001"
      - "10087:8002"
      - "8080:8080"
      - "5900:5900"
    environment:
      - TEMP_DIR=/home/app/.wine/drive_c/data
    volumes:
      - ./data/data:/home/app/.wine/drive_c/data
      - ./data/wechat:/home/app/.wine/drive_c/users/app/Documents/WeChat Files
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8001" ]
      interval: 30s
      timeout: 20s # 一般是20s旁边完成注入
      retries: 3